FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker \
    dagster-dbt

# Set $DAGSTER_HOME and copy dagster.yaml and workspace.yaml there
ENV DAGSTER_HOME=/opt/dagster/app/

# Add repository code
COPY dagster/dagster_chinook/definitions.py  $DAGSTER_HOME/dagster_chinook/definitions.py

RUN mkdir -p $DAGSTER_HOME

COPY dagster/dagster.yaml dagster/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME
