version: "3"
services:
  dbt:
    container_name: dbt-chinook
    image: dbt-apple:latest
    volumes:
      - .:${CONTAINER_PROJECT_DIR}
    env_file:
      - .env
    environment:
      - DBT_PROFILES_DIR=${CONTAINER_PROJECT_DIR}/profiles
    networks:
      - dbt-network
    ports:
      - "8080:8080" # docs
    entrypoint: ["${CONTAINER_PROJECT_DIR}/scripts/entrypoint.sh"]
    # command: |
    #   sh -c "
    #   dbt init chinook_analytics --skip-profile-setup
    #   tail -f /dev/null
    #   "

networks:
  dbt-network:
    driver: bridge
