FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance
RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-dbt



# Add repository code
COPY dbt/chinook_analytics/ /opt/dagster/dbt/chinook_analytics

WORKDIR /opt/dagster/app

COPY dagster/dagster_chinook/definitions.py dagster_chinook/
COPY dagster .

RUN pip install -e .

# Run dagster gRPC server on port 4000

EXPOSE 4000

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "dagster_chinook/definitions.py"]
