version: 2

models:
  - name: stg_chinook__artists
    description: "{{ doc('stg_chinook__artists') }}"
    columns:
      - name: artist_id
        description: "Primary key, unique identifier for each artist"
        tests:
          - not_null
          - unique
      - name: name
        description: "Artist/band name (cleaned and trimmed)"
        tests:
          - not_null
