version: 2

models:
  - name: fact_invoices
    description: "Incremental fact table for invoice lines with dimensional relationships"
    columns:
      - name: invoice_info_key
        description: "Composite surrogate key (invoice_line_id + invoice_id)"
        tests:
          - not_null
          - unique

      - name: customer_key
        description: "Customer surrogate key (FK to dim_customer)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key
              severity: warn

      - name: employee_key
        description: "Employee surrogate key (FK to dim_employee)"
        tests:
          - relationships:
              to: ref('dim_employees')
              field: employee_key
              severity: warn

      - name: date_key
        description: "Date surrogate key (FK to dim_date)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key
              severity: warn

      - name: track_key
        description: "Track surrogate key (FK to dim_track)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_tracks')
              field: track_key
              severity: warn

      - name: invoice_line_id
        description: "Original invoice line ID (business key)"
        tests:
          - not_null

      - name: invoice_id
        description: "Original invoice ID (business key)"
        tests:
          - not_null

      - name: quantity
        description: "Item quantity sold"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 100
              severity: warn

      - name: unit_price
        description: "Item unit price in USD"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.99
              max_value: 20.00
              severity: warn

      - name: total_amount
        description: "Calculated total amount (quantity × unit_price)"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              severity: warn
          - dbt_utils.expression_is_true:
              expression: "= quantity * unit_price"
              severity: error

      - name: dbt_loaded_at
        description: "Timestamp when the record was loaded by dbt"

      - name: dbt_invocation_id
        description: "ID of the dbt run that loaded this record"
